### ISSUE TITLE
How to write letters and numbers to png image IoData?

### ISSUE THREAD

**Issue by leeyisoft** [yuce/png#4]
How to write letters and numbers to png image IoData

I need to implement a picture captch-code function, whether there is a function that can make the alphanumeric distortion, or add some horizontal lines or dots background noise function

**Comment by yuce** [comment]
Hi @leeyisoft, this library doesn't contain that funcitonality, but here are some other libraries that depend on this library:
https://hex.pm/packages?search=depends%3Ahexpm%3Apng
Maybe some of them are useful to give an idea about how to accomplish some of the things you want.

**Comment by leeyisoft** [comment]
I use https://github.com/ziyouchutuwenwu/simple_captcha.git project implements the function of captcha

https://github.com/imboy-pub/imboy/blob/dev/apps/imadm/src/adm_passport_handler.erl

```
captcha(Req, _State) ->
    {CryptKey, BinPng} =  simple_captcha:create(),
    Req2 = cowboy_req:set_resp_cookie(<<"captcha_key">>, CryptKey, Req),
    cowboy_req:reply(200, #{
        <<"content-type">> => <<"image/png; charset=utf-8">>
        , <<"Access-Control-Allow-Origin">> => <<"*">>
    }, BinPng, Req2).
```
